Document: design-pattern
Title: Debian design-pattern Manual
Author: <insert document author here>
Abstract: This manual describes what design-pattern is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/design-pattern/design-pattern.sgml.gz

Format: postscript
Files: /usr/share/doc/design-pattern/design-pattern.ps.gz

Format: text
Files: /usr/share/doc/design-pattern/design-pattern.text.gz

Format: HTML
Index: /usr/share/doc/design-pattern/html/index.html
Files: /usr/share/doc/design-pattern/html/*.html
